### ISSUE TITLE
null pointer exception when doing sum

### ISSUE THREAD

**Issue by ifiddes** [timpalpant/java-genomics-toolkit#3]
```Ians-MacBook-Air Thu Jun 04 12:33 java-genomics-toolkit $./toolRunner.sh wigmath.Add ~/mus_hive/pipeline_data/rnaseq/STAR_output/SPRETEiJ/ebi/liver/ERR476403/Signal.Unique.str1.out.renamed.bw ~/mus_hive/pipeline_data/rnaseq/STAR_output/SPRETEiJ/ebi/liver/ERR476405/Signal.Unique.str1.out.renamed.bw -o t
DEBUG - Executing setup operations
DEBUG - Initializing input files
 INFO - Autodetected BigWig file type: /Users/ifiddes/mus_hive/pipeline_data/rnaseq/STAR_output/SPRETEiJ/ebi/liver/ERR476403/Signal.Unique.str1.out.renamed.bw
 INFO - Autodetected BigWig file type: /Users/ifiddes/mus_hive/pipeline_data/rnaseq/STAR_output/SPRETEiJ/ebi/liver/ERR476405/Signal.Unique.str1.out.renamed.bw
DEBUG - Initialized 2 input files
DEBUG - Found 36 chromosomes in the intersection of all inputs
DEBUG - Initializing thread pool with 1 threads
DEBUG - Performing main computation
DEBUG - Processing chunk 1:3106778-13106777
Exception in thread "main" java.lang.NullPointerException
	at edu.unc.genomics.WigAnalysisTool.run(WigAnalysisTool.java:122)
	at edu.unc.genomics.CommandLineTool.instanceMain(CommandLineTool.java:64)
	at edu.unc.genomics.wigmath.Add.main(Add.java:71)```

**Comment by timpalpant** [comment]
I think this occurs if the input files contain the same chromosome, but have data for disjoint intervals within that chromosome. I've fixed it in commit 26307f336e6907414378640c73612b9794d12d3e. Such a chromosome will now be skipped since there is no overlapping interval of data that can be added.

Thanks!
